### ISSUE TITLE
Please open source ios-constraints-kit to resolve SwiftPackage error

### ISSUE THREAD

**Issue by russshark** [gymshark/ios-stack-kit#5]
Hello guys, its me again 😅 👋🏻

ios-constraints-kit seems to be private and therefore the package cannot be resolved properly.

Would be amazing if you could open source it so I can use this package 🥺

<img width="649" alt="Package Error" src="https://user-images.githubusercontent.com/76947873/170907058-a61f19c4-cd64-44e4-9048-af7b339577d8.png">

Thanks guys, hope you're all doing well 💙🦈

**Comment by TheiOSDude** [comment]
@russshark @tobi404 iOS Constraint Kit _is_ a public repo; https://github.com/gymshark/ios-constraint-kit 

It's possible your SSH isn't too happy, as the dependency referenced in Package.swift (https://github.com/gymshark/ios-stack-kit/blob/b542a829441087d913643b481c9b79d5e0d89596/Package.swift#L16) was a SSH link. 

I have a PR active now, to move the URL to use HTTPS, should see you OK.

Thanks

**Comment by TheiOSDude** [comment]
@tobi404 / @russshark please feel free to update package. We tagged 1.1.1 this morning.
